=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/mine_sala.dtd
<!ELEMENT sala (id,nombre,descripcion,salidas,propiedades,objetos?,encuentros?)>
        <!ATTLIST sala 
                version CDATA #REQUIRED 
                autor  CDATA #REQUIRED 
                area CDATA #REQUIRED 
                comentario CDATA #IMPLIED>

        <!ELEMENT id (#PCDATA)>

        <!ELEMENT nombre (#PCDATA)>

        <!ELEMENT descripcion (item+)>
                <!ELEMENT item (#PCDATA)>
                        <!ATTLIST item 
                               dificultad CDATA #IMPLIED>

        <!ELEMENT salidas (oeste*,este*,norte*,sur*,noroeste*,noreste*,suroeste*,sureste*,arriba*,abajo*,otro*)>

                <!ELEMENT oeste (#PCDATA)>
                        <!ATTLIST oeste 
                                id CDATA #REQUIRED 
                                dificultad CDATA #IMPLIED 
                                 tipo_cierre CDATA #IMPLIED 
                                 estado CDATA #IMPLIED 
                                 datos_cierre CDATA #IMPLIED
                                 mensaje_cerrado CDATA #IMPLIED>
                       
                <!ELEMENT este (#PCDATA)>
                        <!ATTLIST este 
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT norte (#PCDATA)>
                        <!ATTLIST norte
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT sur (#PCDATA)>
                        <!ATTLIST sur
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT noroeste (#PCDATA)>
                        <!ATTLIST noroeste
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT noreste (#PCDATA)>
                        <!ATTLIST noreste
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT suroeste (#PCDATA)>
                        <!ATTLIST suroeste
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT sureste (#PCDATA)>
                        <!ATTLIST sureste 
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT arriba (#PCDATA)>
                        <!ATTLIST arriba
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT abajo (#PCDATA)>
                        <!ATTLIST abajo
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT otro (#PCDATA)>
                        <!ATTLIST otro
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT propiedades (#PCDATA)>
                        <!ATTLIST propiedades 
                                volumen CDATA #REQUIRED
                                luz CDATA #REQUIRED
                                ocultabilidad CDATA #REQUIRED
                                tipo CDATA #IMPLIED
                                aura CDATA #IMPLIED
                                combate CDATA #IMPLIED
                                subtipo CDATA #IMPLIED>

        <!ELEMENT objetos (objeto*)>
                <!ELEMENT objeto (#PCDATA)>
                        <!ATTLIST objeto 
                                id CDATA #REQUIRED 
                                cantidad CDATA #REQUIRED
                                maximo CDATA #IMPLIED
                                probabilidad CDATA #IMPLIED
                                dificultad CDATA #IMPLIED>
        
        <!ELEMENT encuentros (encuentro*)>
                <!ELEMENT encuentro (#PCDATA)>
                        <!ATTLIST encuentro 
                        id CDATA #REQUIRED
                        cantidad CDATA #REQUIRED
                        maximo CDATA #IMPLIED
                        probabilidad CDATA #IMPLIED
                        dificultad CDATA #IMPLIED>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-casa_cocina01.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE saladeMine SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Elenya" area="poblado">
<id>poblado-casa_cocina01</id>
<nombre>Cocina de la casa de Elenya</nombre>
<descripcion>
  <item>Te encuentras en una espaciosa cocina. La luz entra a traves de sus numerosos ventanales, apenas filtrandose por las cortinillas. Bancadas, fogones, utensilios... casi parece mas la cocina de un hobbit que de una elfa.</item>
</descripcion>

<salidas>
  <oeste id="poblado-casa_hall01">Hall</oeste>
  <norte dificultad ='20' id="poblado-casa_despensa01">Rinc√≥n oscuro</norte>
</salidas>

<propiedades volumen='10' luz='50' aura='55' combate="si" ocultabilidad='25'/>

<objetos></objetos>
<encuentros></encuentros>


</sala>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-posada01.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE saladeMine SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Hinuden" area="poblado">
<id>poblado-posada01</id>
<nombre>Salon principal de la posada</nombre>

<descripcion>
    <item>Una sala medianamente grande iluminada suficientemente por una
	lámpara que cuelga del techo y unos cuantos candiles en las paredes.
	Hay ventanas en las paredes que dan al patio y a la calle pero estan
	cerradas con contraventanas de madera. El fuego arde vivamente en la
	chimenea. Frente a ella hay un butacon y a sus pies una vieja alfombra.
	A la derecha estan colocadas tres mesas cuadradas y alargadas
	flanqueadas por largos bancos y presididas a ambos lados por sendos
	taburetes. Tambien hay una mesa redonda rodeada de sillas.</item>
    <item>A la izquierda hay una barra que sirve a la vez de recepcion y de
	dispensador de bebidas. En la esquina mas alejada de la izquierda se
	ve un tramo de escaleras. En el rincón mas alejado de la derecha hay
	un cuartito construido con tablones de madera y separado del salon
	principal por una cortina que hace las veces de reservado. Al frente
	se ve la puerta que da al patio trasero y junto a la barra la puerta
	a las cocinas.</item>
    <item dificultad='18'>Frente a la chimenea la alfombra del suelo tiene
	una arruga. Debajo se ve una trampilla.</item>
</descripcion>

<salidas>
<norte id="poblado-posada_patio01">un [patio]</norte>
<noreste id="poblado-posada_piso01">el [primer] piso</noreste>
<noroeste id="poblado-posada_reservado01">un [reservado]</noroeste>
<sureste id="poblado-posada_cocina01">la [cocina]</sureste>
<oeste id="poblado-calle02">la calle</oeste>
<abajo dificultad='18' id="poblado-posada_bodega01">la [bodega]</abajo>
</salidas>

<propiedades volumen='30' luz='45' aura='50' combate="si"
ocultabilidad='20'/>

<objetos>
    <objeto id="brandy01" probabilidad="20" maximo="4">una botella de [brandy]</objeto>
    <objeto id="cerveza01" probabilidad="40" maximo="10">una jarra de [cerveza]</objeto>
    <objeto id="cerveza02" probabilidad="10" maximo="3">un barril de [cerveza]</objeto>
    <objeto id="garrafa_agua01" probabilidad="40" maximo="6">una garrafa de [agua]</objeto>
    <objeto id="licor01" probabilidad="20" maximo="3">una botella de [licor]</objeto>
    <objeto id="vino01" probabilidad="40" maximo="9">una botella de [vino]</objeto>
    <objeto id="sidra01" probabilidad="30" maximo="7">una botella de [sidra]</objeto>
    <objeto id="pan01" probabilidad="80" maximo="10">un trozo de [pan]</objeto>
</objetos>

<encuentros>
<encuentro id="posadero" probabilidad="0" cantidad="1" dificultad="3">Posadero</encuentro>
</encuentros>

</sala>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-posada_buhardilla01.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE saladeMine SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Hinuden" area="poblado">
<id>poblado-posada_buhardilla01</id>
<nombre>la buhardilla</nombre>

<descripcion>
<item>Cuando logras alcanzar el candil, estiras de él y ves que la puerta se abre. Se despliega una escalera y subes con el candil en la mano.</item>
<item>En esta habitación no hay ventanas. El techo tiene dos vertientes inclinadas a ambos lados pues es ya el último piso. En la parte central puedes andar erguido, pero para observar lo que hay en los rincones te tienes que agachar pues el ángulo del techo es bastante pronunciado</item>
<item>En esta habitación no hay ventanas, y está todo bastante oscuro. A ambos lados puedes ver hileras de grandes baúles cerrados con candados. Cuando llegas al fondo ves que hay un baúl abierto y dentro puedes ver que hay algunas capas y unas cuantas espadas</item>

<item dificultad='23'>****
Hay un palo que sale de detrás del baúl abierto. En el extremo observas que un lienzo está enrollado en él. Cuando lo despliegas ves que es la insignia de Gondor. El árbol blanco, las siete piedras y las siete estrellas
****</item>
</descripcion>

<salidas>
<abajo id="poblado-posada_piso02">el [segundo] piso</abajo>
</salidas>

<propiedades volumen='25' luz='28' aura='44' combate="si"
ocultabilidad='40'/>

<objetos>
</objetos>
<encuentros>
</encuentros>
</sala>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-pozo01.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE saladeMine SYSTEM "mine_sala.dtd">

<sala version="1.2" autor="Hirunatan" area="poblado">

<id>poblado-pozo01</id>
<nombre>Un oscuro y estrecho pozo</nombre>

<descripcion>
<item>Estas en un agujero no muy hondo, pero oscuro, estrecho y sobre todo bastante h√∫medo. Hay poco espacio para moverse. Parece que esto fue antiguamente un pozo para conseguir agua, pero esta abandonado y huele que apesta.</item>
</descripcion>

<salidas>
<arriba id="poblado-camino01">[salir] del pozo</arriba>
</salidas>

<propiedades volumen='3' luz='30' aura='40' combate="si" ocultabilidad='10'/>

<objetos></objetos>
<encuentros></encuentros>

</sala>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-empalizada01.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE sala SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Mandos" area="poblado">
<id>poblado-empalizada01</id>
<nombre>Atalaya Norte</nombre>

<descripcion>
<item>Esta atalaya de madera proporciona una excelente vista de los alrededores y un lugar seguro desde el que defender el poblado contra enemigos. Un pequenyo taburete de madera, muy desgastado por el uso y sujeto al suelo, permite descansar a los ocasionales vigias.</item>
<item>Si diriges tu mirada al sur se muestra ante ti buena parte de la mitad norte del poblado, entre cuyas construcciones destacan una mansion en el lateral de la calle nueva y un extranyo edificio atiborrado de abigarradas estatuas y gargolas en su techo, mas bien al sureste de tu posicion.</item>
<item>Ademas de poder bajar por las escaleras de acceso que ya subiste puedes continuar por el borde de la empalizada tanto hacia el este como hacia el oeste. Sin embargo, si caminas hacia el norte, por el aire, en lugar de caerte ir√°s a parar a un agujero hobbit (cosas de este poblado, ya ves).</item>
</descripcion>

<salidas>
<este id="poblado-empalizada02">por la empalizada</este>
<oeste id="poblado-empalizada03">por la empalizada</oeste>
<abajo id="poblado-calle14">Final de la calle nueva</abajo>
<norte id="Retama-entrada01">el agujero hobbit de la familia Retama</norte>
</salidas>

<propiedades volumen='40' luz='60' aura='50' combate="si" ocultabilidad='10'/>

<objetos></objetos>
<encuentros>
</encuentros>
</sala>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-reservado01.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE saladeMine SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Hinuden" area="poblado-posada">

<id>poblado-reservado01</id>
<nombre>Reservado de la posada</nombre>

<descripcion>
	<item>El cuartito es pequeño y está separado del salón principal por una gruesa cortina. Las paredes son de madera. No está muy claro que tus palabras vayan a ser oidas sólo por tus acomapñantes. El tamaño del cuarto (5X3 metros) Deja el espacio justo para una mesa redonda y 8 sillas pequeñas. Hasta los hobbits se sentirían agobiados aqui.
	La iluminación del cuarto es bastante pobre. Apenas un candil de aceite en cada pared, lo que hace que el centro de la habitación esté en penumbra.</item>
</descripcion> 

<salidas>
	<sureste id="poblado-posada01">Salon principal</sureste>
</salidas>

<propiedades volumen='12' luz='40' aura='45' combate="si"
ocultabilidad='10'/>

<objetos>
</objetos>

<encuentros>
</encuentros>

</sala>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-casa_entrada01.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE saladeMine SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Elenya" area="poblado">
<id>poblado-casa_entrada01</id>
<nombre>La entrada a casa de Elenya</nombre>
<descripcion>
  <item>Una puerta de madera roja te da la bienvenida a casa de Elenya, la elfa.</item>
</descripcion>

<salidas>
  <este id="poblado-casa_hall01">Hall</este>
  <suroeste id="poblado-calle11">Una calle del poblado</suroeste>
</salidas>

<propiedades volumen='15' luz='50' aura='50' combate="si" ocultabilidad='10'/>

<objetos></objetos>
<encuentros></encuentros>
</sala>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-posada_piso02.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE saladeMine SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Hinuden" area="poblado">
<id>poblado-posada_piso02</id>
<nombre>el segundo piso. Habitaciones comunes</nombre>

<descripcion>
<item>El segundo piso es un gran espacio sin paredes por medio. Tan sólo hay columnas para sujetar el techo.</item>

<item>Hay tres filas de camastros dispuestos en paralelo unos con otros. Las dos filas laterales están junto a las paredes. La tercera fila está en el centro de la habitación. Cada fila cuenta con seis camas</item>

<item>Hay tres ventanas en cada pared, una cada dos camas. En las paredes norte y sur hay dos más que dan a las calles que rodean la posada.</item>

<item dificultad='20'>Hay una puerta en el techo. Está en el rincón mas alejado de la escalera. Se intenta disimular con un candil, pero puedes ver las rendijas aun a contraluz</item> 
</descripcion>

<salidas>
<sur id="poblado-posada_piso01">el [primer] piso</sur>
<arriba id="poblado-posada_buhardilla01" dificultad='20'>una [buhardilla]</arriba>
</salidas>

<propiedades volumen='40' luz='50' aura='45' combate="si"
ocultabilidad='15'/>

<objetos>
</objetos>
<encuentros>
</encuentros>
</sala>
