=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/mine_sala.dtd
<!ELEMENT sala (id,nombre,descripcion,salidas,propiedades,objetos?,encuentros?)>
        <!ATTLIST sala 
                version CDATA #REQUIRED 
                autor  CDATA #REQUIRED 
                area CDATA #REQUIRED 
                comentario CDATA #IMPLIED>

        <!ELEMENT id (#PCDATA)>

        <!ELEMENT nombre (#PCDATA)>

        <!ELEMENT descripcion (item+)>
                <!ELEMENT item (#PCDATA)>
                        <!ATTLIST item 
                               dificultad CDATA #IMPLIED>

        <!ELEMENT salidas (oeste*,este*,norte*,sur*,noroeste*,noreste*,suroeste*,sureste*,arriba*,abajo*,otro*)>

                <!ELEMENT oeste (#PCDATA)>
                        <!ATTLIST oeste 
                                id CDATA #REQUIRED 
                                dificultad CDATA #IMPLIED 
                                 tipo_cierre CDATA #IMPLIED 
                                 estado CDATA #IMPLIED 
                                 datos_cierre CDATA #IMPLIED
                                 mensaje_cerrado CDATA #IMPLIED>
                       
                <!ELEMENT este (#PCDATA)>
                        <!ATTLIST este 
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT norte (#PCDATA)>
                        <!ATTLIST norte
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT sur (#PCDATA)>
                        <!ATTLIST sur
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT noroeste (#PCDATA)>
                        <!ATTLIST noroeste
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT noreste (#PCDATA)>
                        <!ATTLIST noreste
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT suroeste (#PCDATA)>
                        <!ATTLIST suroeste
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT sureste (#PCDATA)>
                        <!ATTLIST sureste 
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT arriba (#PCDATA)>
                        <!ATTLIST arriba
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT abajo (#PCDATA)>
                        <!ATTLIST abajo
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT otro (#PCDATA)>
                        <!ATTLIST otro
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT propiedades (#PCDATA)>
                        <!ATTLIST propiedades 
                                volumen CDATA #REQUIRED
                                luz CDATA #REQUIRED
                                ocultabilidad CDATA #REQUIRED
                                tipo CDATA #IMPLIED
                                aura CDATA #IMPLIED
                                combate CDATA #IMPLIED
                                subtipo CDATA #IMPLIED>

        <!ELEMENT objetos (objeto*)>
                <!ELEMENT objeto (#PCDATA)>
                        <!ATTLIST objeto 
                                id CDATA #REQUIRED 
                                cantidad CDATA #REQUIRED
                                maximo CDATA #IMPLIED
                                probabilidad CDATA #IMPLIED
                                dificultad CDATA #IMPLIED>
        
        <!ELEMENT encuentros (encuentro*)>
                <!ELEMENT encuentro (#PCDATA)>
                        <!ATTLIST encuentro 
                        id CDATA #REQUIRED
                        cantidad CDATA #REQUIRED
                        maximo CDATA #IMPLIED
                        probabilidad CDATA #IMPLIED
                        dificultad CDATA #IMPLIED>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-prision03.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE saladeMine SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Mandos" area="poblado">
<id>poblado-prision03</id>
<nombre>Pasillo central</nombre>

<descripcion>
<item>Aqui termina un largo pasillo pobremente iluminado por antorchas que se encamina hacia el oeste desde esta posicion. Hay dos puertas de metal, una al norte y otra al sur, en las que se han practicado pequenyas ranuras a la altura de los ojos y que parecen dar acceso a un par de celdas.</item>
<item>La celda del norte esta abierta y parece que hubo alguien encerrado alli hasta hace no mucho.</item>
</descripcion>

<salidas>
<norte id="poblado-prision03_celda01">celda</norte>
<sur id="poblado-prision03_celda02">celda</sur>
<oeste id="poblado-prision02">pasillo oscuro</oeste>
</salidas>

<propiedades volumen='20' luz='27' aura='40' combate="si"
ocultabilidad='20'/>

<objetos></objetos>
<encuentros></encuentros>
</sala>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-camino01.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE saladeMine SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Mandos" area="poblado" comentario="">
<id>poblado-camino01</id>
<nombre>el camino al Poblado sin nombre</nombre>
<descripcion>
    <item>Tus pasos te dirigen, a través de un camino polvoriento y poco transitado, hacia un pequeño poblado rodeado por una empalizada de madera. Hacia el este puedes vislumbrar las estribaciones de las imponentes Montañas Nubladas.</item>
    <item>Parece que hay movimiento junto al portalón de entrada al poblado.
        <personaje_mira>
	    <requisito comparador="mayor" dificultad="15" id_tirada="percepcion_sala" nombre="resultado_tirada" base="Personaje" valor="1"/>
	</personaje_mira>
    </item>
</descripcion>
<salidas>
    <norte id="poblado-puerta01">entrada al poblado</norte>
    <oeste id="poblado-camino02">senda polvorienta</oeste>
    <abajo id="poblado-pozo01">un oscuro y estrecho [pozo]</abajo>
</salidas>
<propiedades volumen='60.0' luz='70' aura='50' combate="si" ocultabilidad='10'/>
<objetos>
    <objeto id="pocion01" probabilidad="20">Una rara [botellita]</objeto>
    <objeto id="tomillo01" probabilidad="20">Unas ramitas que huelen muy bien</objeto>
</objetos>
<encuentros>
    <encuentro id="tutora" probabilidad="100">La Tutora</encuentro>
</encuentros>
</sala>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-empalizada02.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE sala SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Mandos" area="poblado">
<id>poblado-empalizada02</id>
<nombre>Atalaya Este</nombre>

<descripcion>
<item>En este punto de la empalizada se abre otra pequenya atalaya de madera que vigila el valle ondulado formado entre el poblado y las Montanyas Nubladas. El poblado entiendes ahora que se encuentra ubicado en el limite con un imponente barranco que en este punto casi se une a la empalizada. Tambien aqui hay un taburete sujeto al suelo.</item>
<item>Este es el lugar del que es mas improbable esperar un ataque y por ello se encuentra mucho menos frecuentado.</item>
<item>Si giras tu vista hacia el pueblo ves la calle de los comerciantes, atestada de gente enzarzados en sus tratos cotidianos. Puedes seguir caminando por el borde de la empalizada en direccion norte o sur.</item>
</descripcion>

<salidas>
<norte id="poblado-empalizada01">por la empalizada</norte>
<sur id="poblado-empalizada04">por la empalizada</sur>
</salidas>

<propiedades volumen='40' luz='60' aura='50' combate="si"
ocultabilidad='10'/>

<objetos></objetos>
<encuentros>
</encuentros>
</sala>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-prision02_celda02.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE sala SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Mandos" area="poblado">
<id>poblado-prision02_celda02</id>
<nombre>Celda</nombre>

<descripcion>
<item>Estas en una celda de la prision del poblado. A tu alrededor se extiende la oscuridad que no consigue alumbrar el minusculo resquicio de luz procedente del pasillo. Tampoco hay mucho que ver pues entre las cuatro paredes de dura piedra no hay objeto alguno, ni tan siquiera un jergon de paja o un taburete que sirva para descansar sin sentarse en el frio suelo. Se trata de un lugar tetrico y deprimente.</item>
<item>La unica salida aparente es la puerta de metal que queda al norte.</item>
</descripcion>

<salidas>
<norte id="poblado-prision02">pasillo oscuro</norte>
</salidas>

<propiedades volumen='05' luz='10' aura='38' combate="si"
ocultabilidad='30'/>

<objetos></objetos>
<encuentros>
</encuentros>
</sala>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-camino03.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE sala SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Hizgael" area="poblado">
<id>poblado-camino03</id>
<nombre>Bordeando la Empalizada</nombre>

<descripcion>
<item>Encuentras que la maleza es tan espesa que te impide el paso.</item>
</descripcion>

<salidas>
<este id="poblado-camino02">senda entre matorrales</este>
</salidas>

<propiedades volumen='40' luz='45' aura='45' combate="si"
ocultabilidad='60'/>

<objetos></objetos>
<encuentros>
</encuentros>
</sala>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-prision02.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE saladeMine SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Mandos" area="poblado">
<id>poblado-prision02</id>
<nombre>Pasillo central</nombre>

<descripcion>
<item>Estas en mitad de un sucio y oscuro pasillo de piedra que continua en direccion este y oeste. Dos puertas de metal a ambos lados de la pared dan acceso a lo que deben ser celdas, por lo que imaginas tras haber echado un vistazo a las mismas desde una pequenya ranura que tienen a la altura de los ojos.</item>
<item>No estas seguro de si hay alguien encerrado en las celdas pues se encuentran casi completamente a oscuras.</item>
</descripcion>

<salidas>
<norte id="poblado-prision02_celda01">celda</norte>
<sur id="poblado-prision02_celda02">celda</sur>
<este id="poblado-prision03">pasillo oscuro</este>
<oeste id="poblado-prision01">pasillo oscuro</oeste>
</salidas>

<propiedades volumen='20' luz='27' aura='40' combate="si"
ocultabilidad='20'/>

<objetos></objetos>
<encuentros></encuentros>
</sala>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-cuartel01.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE saladeMine SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Mandos" area="poblado" comentario="">
<id>poblado-cuartel01</id>
<nombre>Entrada al Cuartel</nombre>
<descripcion>
    <item>Estas en una pequenya sala limpia y vacia de muebles. De cuando en cuando pasa algun guardia, a veces con alguien fuertemente sujeto, y traspasan puerta que hay hacia el sur. Otra puerta, mucho mas grande, conduce fuera del edificio, a la calle.</item>
</descripcion>
<salidas>
    <sur id="poblado-cuartel02">interior del cuartel</sur>
    <oeste id="poblado-calle08">calle</oeste>
</salidas>
<propiedades volumen='15.0' luz='30' aura='55' combate="si" ocultabilidad='5'/>
<objetos>
</objetos>
<encuentros>
</encuentros>
</sala>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-posada_cocina01.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE sala SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Hinuden" area="poblado-posada">

<id>poblado-posada_cocina01</id>

<nombre>la cocina de la posada</nombre>

<descripcion>
<item>Una cocina de tamaño mediano, pero que por la gran cantidad de muebles parece más pequeña. El suelo es de tablas de madera. Hay un gran banco de madera pulida que recorre toda la pared de enfrente. En la pared de la derecha está la cocina de leña. Hay una gran mancha de hollín en la pared, justo debajo del tubo que lleva el humo al exterior. A la derecha, en la pared frente al banco, hay una mesa de carnicero. Tiene muchos cortes. Junto a la mesa de carnicero hay una ventana amplia sin cristales ni contraventanas y da justo a la barra del salón.</item>
<item>Por la pared del norte, colgados encima del banco, hay una hilera de armarios. Algunos están abiertos y puedes ver que contienen cacerolas, pucheros, sartenes y cosas así. Un gran candil está colgado del techo e ilumina sobradamente la habitación.</item>

<item dificultad='5'>En todas las paredes de la cocina se pueden ver manchas de grasa. Sin duda se cocina mucha carne en esta cocina</item>

<item dificultad='15'>En el suelo se puede ver una puerta. No hay estirador para abrirla, pero ves las rendijas</item>

</descripcion>

<salidas>
<suroeste id="poblado-posada01">el [salon] principal</suroeste>
<abajo dificultad='15' id="poblado-posada_bodega01">la [bodega]</abajo>
</salidas>

<propiedades volumen='8' luz='55' aura='55' combate="si" ocultabilidad='11'/>

<objetos>
    <objeto id="huevo01" cantidad="1" probabilidad="80" maximo="10">un huevo de gallina</objeto>
    <objeto id="sarten01" cantidad="1" probabilidad="80" maximo="1">una sarten</objeto>
    <objeto id="cocina01" cantidad="1">una cocina de leña</objeto>
</objetos>

<encuentros>
</encuentros>

</sala>
