=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/mine_sala.dtd
<!ELEMENT sala (id,nombre,descripcion,salidas,propiedades,objetos?,encuentros?)>
        <!ATTLIST sala 
                version CDATA #REQUIRED 
                autor  CDATA #REQUIRED 
                area CDATA #REQUIRED 
                comentario CDATA #IMPLIED>

        <!ELEMENT id (#PCDATA)>

        <!ELEMENT nombre (#PCDATA)>

        <!ELEMENT descripcion (item+)>
                <!ELEMENT item (#PCDATA)>
                        <!ATTLIST item 
                               dificultad CDATA #IMPLIED>

        <!ELEMENT salidas (oeste*,este*,norte*,sur*,noroeste*,noreste*,suroeste*,sureste*,arriba*,abajo*,otro*)>

                <!ELEMENT oeste (#PCDATA)>
                        <!ATTLIST oeste 
                                id CDATA #REQUIRED 
                                dificultad CDATA #IMPLIED 
                                 tipo_cierre CDATA #IMPLIED 
                                 estado CDATA #IMPLIED 
                                 datos_cierre CDATA #IMPLIED
                                 mensaje_cerrado CDATA #IMPLIED>
                       
                <!ELEMENT este (#PCDATA)>
                        <!ATTLIST este 
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT norte (#PCDATA)>
                        <!ATTLIST norte
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT sur (#PCDATA)>
                        <!ATTLIST sur
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT noroeste (#PCDATA)>
                        <!ATTLIST noroeste
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT noreste (#PCDATA)>
                        <!ATTLIST noreste
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT suroeste (#PCDATA)>
                        <!ATTLIST suroeste
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT sureste (#PCDATA)>
                        <!ATTLIST sureste 
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT arriba (#PCDATA)>
                        <!ATTLIST arriba
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT abajo (#PCDATA)>
                        <!ATTLIST abajo
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT otro (#PCDATA)>
                        <!ATTLIST otro
                                  id CDATA #REQUIRED 
                                  dificultad CDATA #IMPLIED 
                                  tipo_cierre CDATA #IMPLIED 
                                  estado CDATA #IMPLIED 
                                  datos_cierre CDATA #IMPLIED
                                  mensaje_cerrado CDATA #IMPLIED>

                <!ELEMENT propiedades (#PCDATA)>
                        <!ATTLIST propiedades 
                                volumen CDATA #REQUIRED
                                luz CDATA #REQUIRED
                                ocultabilidad CDATA #REQUIRED
                                tipo CDATA #IMPLIED
                                aura CDATA #IMPLIED
                                combate CDATA #IMPLIED
                                subtipo CDATA #IMPLIED>

        <!ELEMENT objetos (objeto*)>
                <!ELEMENT objeto (#PCDATA)>
                        <!ATTLIST objeto 
                                id CDATA #REQUIRED 
                                cantidad CDATA #REQUIRED
                                maximo CDATA #IMPLIED
                                probabilidad CDATA #IMPLIED
                                dificultad CDATA #IMPLIED>
        
        <!ELEMENT encuentros (encuentro*)>
                <!ELEMENT encuentro (#PCDATA)>
                        <!ATTLIST encuentro 
                        id CDATA #REQUIRED
                        cantidad CDATA #REQUIRED
                        maximo CDATA #IMPLIED
                        probabilidad CDATA #IMPLIED
                        dificultad CDATA #IMPLIED>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-camino02.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE sala SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Hizgael" area="poblado">
<id>poblado-camino02</id>
<nombre>Bordeando la Empalizada</nombre>

<descripcion>
<item>Una pequeña senda rodea la empalizada del poblado. La maleza crece por todas partes.</item>
<item dificultad='10'>Hay una pequeña grieta en la empalizada semioculta entre matorrales. Una persona no muy gruesa podría pasar.</item>
</descripcion>

<salidas>
<este id="poblado-camino01">puertas de la ciudad</este>
<oeste id="poblado-camino03">senda entre matorrales</oeste>
<norte id="poblado-calle04" dificultad='10'>grieta</norte>
</salidas>

<propiedades volumen='40' luz='55' aura='45' combate="si"
ocultabilidad='40'/>

<objetos></objetos>
<encuentros>
</encuentros>
</sala>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-posada_patio01.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE saladeMine SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Hinuden" area="poblado">
<id>poblado-posada_patio01</id>
<nombre>Patio trasero y cuadra de la posada</nombre>

<descripcion>
	<item> Un gran patio se abre en la parte trasera de la posada. A la derecha se pueden ver un cobertizo pequeño en el que se cobijan unos toneles que tienen pintada una marca en rojo que reza "Hinuden 2002". Parecen ser de cerveza.</item>
<item>Un poco mas adelante, en el mismo lado, se pueden apreciar unas largas palanganas y una fuente. Se ven unas cuantas piedras de lavado.</item>

<item> A la izquierda hay un gran cobertizo con una pared hasta la altura de un hobit. Una puerta permite el acceso y dentro se pueden ver pequeñas habitaciones con paja y alfalfa. Hay bebederos y comederos para los caballos que se hospeden alli.</item>

<item dificultad='15'> Siguiendo la pared en la que esta la puerta al salon principal, hay una pequeña puerta justo en la esquina.</item>

<item> Entre el cobertizo y el labadero, hay una puerta grande de dos ojas por la que seguramente entran los carros y los caballos de los huespedes</item>
</descripcion>

<salidas>
<norte id="poblado-calle06">[porton]</norte>
<noroeste id="poblado-posada_bodega01">[puertecita]</noroeste>
<oeste id="poblado-posada01">[salon]</oeste>
</salidas>

<propiedades volumen='50' luz='45' aura='50' combate="si"
ocultabilidad='30'/>

<objetos>
</objetos>
<encuentros>
</encuentros>
</sala>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-posada_reservado01.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE saladeMine SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Hinuden" area="poblado-posada">

<id>poblado-posada_reservado01</id>
<nombre>el Reservado de la posada</nombre>

<descripcion>
	<item>El cuartito es pequeño y está separado del salón principal por una gruesa cortina. Las paredes están hechas de tablas de madera y se ven huecos en las rendijas. El tamaño del cuarto deja el espacio justo para una mesa redonda y 8 sillas pequeñas. Hasta los hobbits se sentirían agobiados aquí.
	La iluminación del cuarto es bastante pobre. Apenas un candil de aceite colgando del techo.</item>
</descripcion> 

<salidas>
	<sureste id="poblado-posada01">[salon] principal</sureste>
</salidas>

<propiedades volumen='12' luz='40' aura='45' combate="si"
ocultabilidad='10'/>

<objetos>
</objetos>

<encuentros>
</encuentros>

</sala>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-cuartel02.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE saladeMine SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Mandos" area="poblado" comentario="">
<id>poblado-cuartel02</id>
<nombre>Interior del Cuartel</nombre>
<descripcion>
    <item>Esta habitacion amplia y despejada cuenta como unicos muebles con una especie de mostrador de madera oscura muy desgastada y una silla detras del mismo material. Por lo demas se encuentra vacia. Constantemente pasean por aqui guardias procedentes de todas las direcciones sin prestarte mucha atencion. Algunos permanecen un buen rato tras el mostrador y se hacen cargo de las pertenencias de los presos cuando son traidos por los guardias.</item>
    <item>Hacia el norte hay una pequenya sala de entrada al lugar, mientras que al este se yergue una fuerte puerta con todos los visos de estar cerrada. Al sur, cerca del mostrador, unas escaleras conducen a un oscuro corredor.</item>
    <item dificultad='15'>Al cabo de un rato de observar a los guardias te percatas de que a los prisioneros se los llevan por las escaleras del sur.</item>
</descripcion>
<salidas>
    <norte id="poblado-cuartel01">sala de entrada</norte>
    <este id="poblado-cuartel03">puerta cerrada</este>
    <abajo id="poblado-prision01">pasillo oscuro</abajo>
</salidas>
<propiedades volumen='25.0' luz='30' aura='55' combate="si" ocultabilidad='10'/>
<objetos>
</objetos>
<encuentros>
    <encuentro id="alguacil01" probabilidad="100" cantidad="1" maximo="1">el alguacil</encuentro>
</encuentros>
</sala>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-casa_hall01.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE sala SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Elenya" area="poblado">
<id>poblado-casa_hall01</id>
<nombre>Hall de la casa de Elenya</nombre>
<descripcion>
  <item>Te encuentras en una pequenya habitacion, con las paredes forradas de paneles de la misma madera roja que la puerta.</item>
</descripcion>

<salidas>
  <oeste id="poblado-casa_entrada01">Puerta</oeste>
  <este id="poblado-casa_cocina01">Cocina</este>
  <norte id="poblado-casa_pasillo01">Pasillo</norte>
</salidas>
<propiedades volumen='6' luz='50' aura='55' combate="si" ocultabilidad='15'/>

<objetos></objetos>
<encuentros>
</encuentros>
</sala>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-posada_bodega01.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE saladeMine SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Hinuden" area="poblado-posada">

<id>poblado-posada_bodega01</id>

<nombre>la bodega de suministros</nombre>

<descripcion>
<item>Ves un hueco del tamaño de una mano en la puerta. Estiras y la abres. Ves una escalera que baja unos 10 peldaños. Abajo está muy oscuro. Sólo la luz que viene de la puerta abierta te permite entrever cómo es la bodega. Un cuarto de dos pasos de ancho y cuatro de largo, con un fortísimo olor a embutidos. Puedes ver a medias las ristras de longanizas, chorizos y demás embutidos que cuelgan del techo. También ves unos cuantos jamones que están junto a la pared del norte. El ambiente del cuerto es seco, propio de un secadero. El suelo está recubiero de paja limpia y seca para secar más el ambiente. Puedes ver que en la pared del sur hay una estantería que llega hasta el techo. En ella ves tarros de especias, pequeños sacos de harina, sal y azucar, sacos de arroz, bandejas de pollo frío, y también adviertes algunos libros.</item>

<item>Las salidas se encuentran al este y al oeste. Sendas escaleras que llevan a una puerta y a la trampilla de la cocina respectivamente</item>
</descripcion>

<salidas>
<arriba id="poblado-posada_cocina01">la [cocina]</arriba>
<arriba id="poblado-posada_patio01">el [patio]</arriba>
</salidas>

<propiedades volumen='5' luz='7' aura='50' combate="si" ocultabilidad='40'/>

<objetos></objetos>

<encuentros></encuentros>

</sala>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-posada_piso01_habitacion08.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE saladeMine SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Hinuden" area="poblado">
<id>poblado-posada_piso01_habitacion08</id>
<nombre>la habitación número ocho</nombre>

<descripcion>
<item>La habitación, como las demás, está iluminada y aireada por una ventana de guillotina, es relativamente amplia. Una cama junto a la ventana y una pequeña mesa en el rincon izquierdo. A la derecha de la puerta hay una mesa redonda con cuatro sillas a su alrededor, aun así hay algun espacio para andar. En el rincón de la derecha hay una mesa con una palangana y una jarra. Colgando de la pared, un espejo cuadrado y de tamaño justo para verse sólo la cara.</item>

<item>Encima de la mesa grande y de la pequeña junto a la cama, hay sendos candiles de aceite para iluminar por la noche.</item>

<item>Junto a la mesa para lavarse hay una cajonera amplia que comprende cuatro cajones para ropa</item>

</descripcion>

<salidas>
<oeste id="poblado-posada_piso01">al [pasillo]</oeste>
</salidas>

<propiedades volumen='10' luz='40' aura='45' combate="si"
ocultabilidad='12'/>

<objetos>
</objetos>
<encuentros>
</encuentros>
</sala>

=== PIWEEK/mine-eiffel/data/world_definition/places/poblado/poblado-prision01.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE sala SYSTEM "mine_sala.dtd">
<sala version="1.2" autor="Mandos" area="poblado">
<id>poblado-prision01</id>
<nombre>Pasillo central</nombre>

<descripcion>
<item>Este lugar esta debilmente iluminado por antorchas colocadas a intervalos regulares en la pared. Se trata del inicio de un largo y sucio pasillo que se pierde hacia el este.</item>
<item>Unas escaleras suben en direccion norte hacia una habitacion con mas luz.</item>
</descripcion>

<salidas>
<arriba id="poblado-cuartel02">sala de entrada</arriba>
<este id="poblado-prision02">pasillo oscuro</este>
</salidas>

<propiedades volumen='20' luz='27' aura='40' combate="si"
ocultabilidad='20'/>

<objetos></objetos>
<encuentros>
</encuentros>
</sala>
